### ISSUE TITLE
[Beacon] more descriptive content for incorrect Carbon for IBM.com version

### ISSUE THREAD

**Issue by kennylam** [IBM/beacon-for-ibm-dotcom#27]
The `dds-version-check-audit` audit checks the page to see if the Carbon for IBM.com package version is present in the Digital Data Object, and if so, if it is the latest version. If the version being used is older than the latest version of Carbon for IBM.com, the audit will alert the user. This copy can be more informative than it currently is. Users should be aware that by using older versions, other audits could also fail.

Also, the `Learn more` link currently points to the [Digital Data Object](https://github.com/carbon-design-system/carbon-for-ibm-dotcom/blob/master/docs/building-for-ibm-dotcom.md#digital-data-object) page, which for package version, is not very helpful at all. Comparing releases might be a bit too granular – perhaps more general copy informing users of the disadvantages/issues of using older versions?

![image](https://user-images.githubusercontent.com/909118/134550606-86403984-1433-46fe-a2dc-2b26edeeff1f.png)

**Comment by janchild** [comment]
@kennylam Thanks for describing the requirements for the message. That helped a lot. Here is a first pass at new content. I wanted to see if we could reorder the content at the top and make the warning sentence the red sentence. Some other things:
- I removed the word `stable`. Is it really necessary?
- I also shortened the two sentences referencing the version. They may need to include Carbon for IBM.com but maybe not if they are always paired with the warning sentence above.  
- I wrote two paragraphs. You could skip the second one if you think this is getting too long. I wrote it so that we could end on a positive.

Anyway, let me know what you think. Happy to adjust any way we need to! 

![Beacon version message](https://user-images.githubusercontent.com/44503588/137375612-6ca7defd-4b53-40c2-aafe-82d14e7bbd14.png)
